### ISSUE TITLE
can't login and no userSettings.json pressent

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [ToonSoftwareCollective/postnl#8]
I've no idea how i should login. I know my postnl password but i have no idea what my userId is and i can't find any installation guide anywhere.
I've tried using my email (the one i use to login in the postNL app)

I tried to check the userSettings in the SSH but there is no present.
![image](https://user-images.githubusercontent.com/1246691/116002273-3df77780-a5f9-11eb-987c-2d343e53f5e2.png)

**Comment by ToonzDev** [comment]
user settings are stored in /mnt/data/tsc/postnl.userSettings.json by the way.
You do not need to edit this file, can be done via the app's 'Instellingen' page from the main screen.
But you do need to find out your userid of course for the app to work (usually this is the email address you used to signup for the Postnl account).

**Comment by ricardovanlaarhoven** [comment]
I've found the json file, thnx!
The info is stored in there correctly but it still doesn't fetch any data.

is there any way i can debug this?
i'm using my mailadress which i also use to login in the postnl app and the website. Is that correct?

**Comment by ToonzDev** [comment]
you can follow progress on /var/tmp/postnl, several temporary files there which can show error messages..... 

⁣BlueMail voor Android downloaden ​

Op 26 apr. 2021 10:32, om 10:32, Ricardo van Laarhoven ***@***.***> schreef:

**Comment by ricardovanlaarhoven** [comment]
postnl-resp1.tm says
`Invalid return URL specified`

and the toon keeps loading
