### ISSUE TITLE
Can't run ./postnl.sh

### ISSUE THREAD

**Issue by prvashisht** [ToonSoftwareCollective/postnl#9]
Hi,

I'm trying to use the shell script to get the json of packages like this 
`./postnl.sh -u "myawesomeemail@website.com" -p "MyAwesomePassword" -d "/tmp/postnl"`

I get this
```
No recent access code. Start login postnl sequence.
Error: Wrong responsecode
400 received from Account/Login step 1 request. See /tmp/postnl/postnl-resp1.tmp. Aborting.
```

The file has just this text `Invalid return URL specified%`

Any help? thanks!

**Comment by glsf91** [comment]
In a few days there will be a working script (if postnl does not break it in the upcoming days)

**Comment by glsf91** [comment]
It is solved for now with the new release.
